# Generated by Django 4.1.7 on 2023-11-05 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuizData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz_uuid", models.UUIDField()),
                ("question_uuid", models.UUIDField(default=uuid.uuid4)),
                ("question", models.CharField(max_length=1000)),
                ("option_a", models.CharField(max_length=1000)),
                ("option_b", models.CharField(max_length=1000)),
                ("option_c", models.CharField(max_length=1000)),
                ("option_d", models.CharField(max_length=1000)),
                ("code", models.CharField(blank=True, max_length=2000, null=True)),
                ("answer", models.CharField(max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
            ],
        )
    ]
